### ISSUE TITLE
Formula mejor esta frase

### ISSUE THREAD

**Issue by JJ** [JoseJordanF/Claqueta#10]
Quizás mejor "entretenimiento *que se deriva de los productos*". O hablar de "capacidad" de entretenimiento. En todo caso, relee con cuidado y reformula.

https://github.com/JoseJordanF/Claqueta/blob/bb176c901ef00dddcac6e217952b640e10263103/doc/secciones/01_introduccion.tex#L5

**Comment by JJ** [comment]
Los issues es mejor que los trates de resolver en un PR, que se refiera al mismo.

**Comment by JoseJordanF** [comment]
De acuerdo en los próximos commit los haré con otra rama para iniciar el PR.
