### ISSUE TITLE
Montar sistema de integración continua

### ISSUE THREAD

**Issue by JJ** [JoseJordanF/Claqueta#107]
En el momento que estás creando tests, tienes que pasarlos automáticamente. De hecho, deberías haberlos incluido ya en el PR último #103. Voy a quitar la revisión para que no fusiones hasta que no tengas los tests.

**Comment by JoseJordanF** [comment]
[27f2284](https://github.com/JoseJordanF/Claqueta/pull/103/commits/27f2284ad2418e43e02e8eece17976d63c728cd8)

**Comment by JJ** [comment]
Convendría que te acostumbraras a cerrar desde un commit o desde el cuerpo del PR. En un PR no tienes más que poner `closes #xx` y no sólo lo cierra, sino que además en el mismo PR aparecen los issues que se van a cerrar.
