### ISSUE TITLE
Plantea el problema claramente, a la vez que el contexto.

### ISSUE THREAD

**Issue by JJ** [JoseJordanF/Claqueta#11]
https://github.com/JoseJordanF/Claqueta/blob/bb176c901ef00dddcac6e217952b640e10263103/doc/secciones/01_introduccion.tex#L3

Estás planteando el contexto, pero no el problema. El problema no es que la gente quiera hacer reseñas, tienes que poner la motivación para que la gente haga reseñas, o para que lea esas reseñas; en función de eso se derivará la funcionalidad que quieras añadir: valorar las reseñas, por ejemplo, o contestar a las reseñas, o lo que sea. Sin un problema claramente formulado, cualquier funcionalidad que plantees se queda en el aire y no "soluciona" nada, porque no hay qué solucionar.

**Comment by JoseJordanF** [comment]
O sea que no vale que plantee el problema solo en el capítulo 2 también debo presentarlo en la introducción.
