### ISSUE TITLE
Que pasa si en el futuro se quiere cambiar la implementación de la capa

### ISSUE THREAD

**Issue by JoseJordanF** [JoseJordanF/Claqueta#117]
¿Si en producción se quisiera cambiar la implementación de la capa de persistencia, habría que cambiar todo el código? #1

**Comment by JJ** [comment]
Los issues deben ser planteamiento de problemas. En este caso, no queda claro cuál es el problema. Asignarlo directamente una historia de usuario tampoco aclara demasiado el contexto.
