### ISSUE TITLE
Que son los logs y porque los necesitamos

### ISSUE THREAD

**Issue by JoseJordanF** [JoseJordanF/Claqueta#119]
Que son estos registros y porque los necesitamos en la persistencia de datos y en el proyecto #1

**Comment by JJ** [comment]
Una vez más, poner simplemente una historia de usuario no va a ayudar a resolver el problema. Si no dices claramente en qué contexto, nivel de abstracción, tipo de despliegue y demás, es imposible resolverlo correctamente. Puedes poner una cosa en los logs, dos o ninguna, va a dar exactamente igual.
Aparte de las historias de usuario, debes plantear en los milestones cuáles son los requisitos técnicos que vas a usar. La descripción del milestone se comporta como una historia de usuario, pero para los operadores o desarrolladores.
Ahora mismo dices que se va a "establecer" la persistencia de datos, pero no dices qué es ni qué la haría válida. También dices simplemente "establecer los logs" pero no dices por qué los quieres ni cómo vas a usarlos.

**Comment by JoseJordanF** [comment]
Si la verdad que no los contextualizo, y hay algunos que se entienden, pero en la mayoría de los casos necesito o poner un título más descriptivo o contextualizar mejor el problema
