### ISSUE TITLE
¿Los críticos forman parte de la industria cinematográfica?

### ISSUE THREAD

**Issue by JJ** [JoseJordanF/Claqueta#12]
¿O son externos y eso es lo bueno?

https://github.com/JoseJordanF/Claqueta/blob/bb176c901ef00dddcac6e217952b640e10263103/doc/secciones/01_introduccion.tex#L43

Por otro lado, debes tener cierto cuidado con qué es lo que justificas con la descripción del contexto; por eso también tienes que hacerlo *después* de la formulación del problema.

**Comment by JoseJordanF** [comment]
He reformulado la frase para que no parezca que trabajan dentro de la industria, sino que les hacen un gran favor.
