### ISSUE TITLE
Como desarrollador, quiero una herramienta que permita dotar a mi aplicación de un sistema de configuración

### ISSUE THREAD

**Issue by JoseJordanF** [JoseJordanF/Claqueta#125]
Tal como se menciona en 3º hito como desarrollador busco herramientas que me permitan dotar de dos funcionalidades esenciales a mi aplicación:

La primera funcionalidad, un sistema de configuración que me permita arrancar mi aplicación obteniendo los secretos(variables sensibles, como IPs, paths de ficheros o claves API para el uso de servicios en la nube) que necesite para el funcionamiento de esta. La práctica más habitual es que estos secretos sean variables de entorno seguras que podamos cargar desde nuestra aplicación, siendo estos identificados por algo distintivo al nombrar todos los secretos que necesitamos para nuestra aplicación.

A su vez, necesito que sea capaz de cargar estos secretos de distintas fuentes, ya que es común que estos provengan de varias fuentes, por lo que si solo nos centramos en una fuente y esta falla, la aplicación ni siquiera arrancaría. En este caso busco que sea capaz de leer de distintas fuentes populares en Kotlin e indudablemente de fuentes frecuentes en todos los entornos, como las variables de entorno del sistema. 

Una vez descubiertas estas fuentes se impondrá una jerarquía a la hora de leer estas.

**Comment by JJ** [comment]
A ver, "historia de desarrollador" no parece un cuerpo suficientemente descriptivo, ¿no te parece?
Aparte, ¿quieres decir ficheros de configuración en vez de fuentes?

Recuerda que lo esencial es que esto esté en la descripción del PMV del M3

**Comment by JoseJordanF** [comment]
a vale yo creia que lo tenía que hacer en un issue

**Comment by JJ** [comment]
Las historias de desarrollador son iguales que las historias de usuario, en el sentido que indican un problema, y tienen que estar en el dominio del problema. No se puede decir "quiero usar una biblioteca", sino qué problema quieres resolver con esa biblioteca. Si no tienes claro cuál es el problema que quieres resolver, no puedes hacer un test y puede salir cualquier cosa. En [el comentario aquí](https://github.com/JoseJordanF/Claqueta/pull/124) creo que he explicado cuál es el problema fundamental, que tendrás que aplicar a tu propio proyecto y lenguaje.

**Comment by JJ** [comment]
> Tal como se menciona en 3º hito como desarrollador busco herramientas que me permitan dotar de dos funcionalidades esenciales a mi aplicación:
> 
> La primera funcionalidad, un sistema de configuración que me permita arrancar mi aplicación obteniendo los secretos(variables sensibles, como IPs, paths de ficheros o claves API para el uso de servicios en la nube) que necesite para el funcionamiento de esta. A su vez, necesito que sea capaz de cargar estos secretos de distintas fuentes, ya que es habitual que estos provengan de varios tipos de archivos, por lo que si solo nos centramos en una fuente y esta falla, la aplicación ni siquiera arrancaría. En este caso busco que sea capaz de leer de distintas fuentes populares en Kotlin e incluso de fuentes comunes en todos los entornos, como las variables de entorno del sistema o a través de ficheros .env
> 

¿Cuál es el formato habitual de esos secretos? Si se usan sistemas genéricos como las variables de entorno, ¿cómo sabe la aplicación qué variables de entorno tiene que leer?

Si se lee de "fuentes populares", ¿es necesario optar por una específica? Si se opta por esa una, ¿qué orden tendrá con respecto a los secretos?

> La segunda funcionalidad, un sistema de registros que me permita obtener control sobre toda la actividad de la aplicación, como por ejemplo si la carga de la configuración es correcta o errónea. Este sistema debe permitirme de manera sencilla registrar logs en las distintas partes del código de forma sencilla y con un formato descriptivo, pudiendo visualizar así el correcto funcionamiento de la aplicación o poder reaccionar a los posibles errores que pudieran estar ocurriendo en esta

Quizás sería conveniente que esto fuera a otra historia de desarrollador. Son problemas diferentes, cada issue debe representar un solo problema.
