### ISSUE TITLE
Como desarrollador, quiero una herramienta que me mantenga informado sobre toda acción en mi aplicación

### ISSUE THREAD

**Issue by JoseJordanF** [JoseJordanF/Claqueta#126]
Tal como se menciona en 3º hito como desarrollador busco herramientas que me permitan dotar de dos funcionalidades esenciales a mi aplicación:

Como desarrollador necesito saber qué pasa en mi aplicación, necesito ver que todo funciona correctamente, y si no lo hace localizar rápidamente el error para poder solucionarlo. Necesito ese control tanto en las acciones que lleva a cabo la aplicación durante su ejecución, como las que lleva a cabo el usuario. Luego necesito una herramienta que me permita tener ese control, esa visibilidad de que todo está como debería o que algo ha fallado, pero sé cuando ha fallado y tengo los datos relevantes al error. Así esta herramienta me debe permitir crear y disponer estos logs donde crea necesario para obtener el estado de la aplicación en toda acción que se realice. De manera que yo pueda observar el comportamiento de todo lo que ocurra en la app o de lo que haga el usuario, tanto por consola o en un archivo que guarde estos logs. El formato de los logs deberá ser un formato legible y común en este ámbito, que me permita parsearlo por si fuera necesario acceder a los datos ofrecidos por ese log en algún momento.

**Comment by JJ** [comment]
Una historia siempre es un problema. "Dotar de un sistema de registros" no es un problema. ¿Para qué quieres los logs? ¿Para qué vas a usarlo?
