### ISSUE TITLE
¿Dónde van a estar los films?

### ISSUE THREAD

**Issue by JJ** [JoseJordanF/Claqueta#128]
Aquí parece indicar que van a estar en este objeto, ¿no? Si es así, ¿por qué se llama UserFilmReviewManager?

https://github.com/JoseJordanF/Claqueta/blob/f24c0e5aa6ae3924846257bf6dff72c4f02daa63/claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManager.kt#L11

Si no es así, sería conveniente que usaras referencias únicas a objetos, en vez de objetos en sí. O que los nombres reflejaran correctamente ese hecho.

**Comment by JoseJordanF** [comment]
No sé a qué te refieres, se llama así porque es quien gestiona de los usuarios, películas y reseñas

**Comment by JJ** [comment]
¿En `films` van a estar los objetos completos o un id del objeto `Film`? ¿`Film` es un objeto o un `Film`? ¿Si es un objeto, va a estar ahí y en ningún otro lado?

**Comment by JoseJordanF** [comment]
No se a que te refieres con esta pregunta ¿Film es un objeto o un Film?. Que sería un film si no es un objeto y otra pregunta donde debería estar en manager gestiona la lista de films

**Comment by JJ** [comment]
¿Hay una sola copia del objeto Film? ¿O una en este objeto, otra en otro objeto que tenga sólo los films, etc?

**Comment by JoseJordanF** [comment]
No solo existe esa lista de Films

**Comment by JJ** [comment]
OK, usa un nombre entonces que revele lo que hace, como `ClaquetaManager`.
Por otro lado, tiene sentido que haya un `Map` para ellos, ¿pero te das cuenta que usar `Long` en vez de un `ID` más genérico implica que tienes que gestionar cómo se genera ese `long`? ¿Y que `reviews` no tienen, a priori, nada que mapee desde film o desde usuario y por tanto la única forma de llegar a una review es revisar todas hasta que coincidan? (no es cosa de este issue, sin embargo)

**Comment by JJ** [comment]
En todo caso, todo esto para una mejora más adelante, pero en todo caso antes de meter persistencia de datos.

**Comment by JoseJordanF** [comment]
No lo entiendo, cuando se hizo esa parte me recomendaste usar SnowFlake para gestionar el ID. Y por lo de la review, contiene el Id de la película y el nombre del usuario, no sé si es eso a lo que te refieres

**Comment by JJ** [comment]
Pero ¿SnowFlake devuelve un tipo específico? Eso es lo que quiero decir con un ID más genérico.

**Comment by JoseJordanF** [comment]
A vale te refieres a que simplemente no use un ID, sino que lo devuelva como un String, que la verdad me viene inmensamente mejor para tratar con él

**Comment by JJ** [comment]
Ah, OK [ya veo](https://github.com/JoseJordanF/Claqueta/blob/f24c0e5aa6ae3924846257bf6dff72c4f02daa63/claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/generatorId/SnowFlake.kt#L4), devuelve un Long
OK, vale por el momento, pero ten en cuenta que no hay nada que fuerce a usar esa función para generar el Long. En principio una clase derivada, o una refactorización, podían simplemente eliminarla.
Vale como MVP en todo caso. Más adelante si quieres refactorizar hazlo así.
En todo caso, si te viene inmensamente mejor, deberías haber escrito clarament en el issue qué es lo que te viene bien. Nadie obliga a que un Map tenga como claves Long; pueden ser string y posiblemente otras cosas.

**Comment by JoseJordanF** [comment]
Vale, pues más adelante lo cambiaré. 

Otra cosa a que referías con lo de la review?

**Comment by JJ** [comment]
> Vale, pues más adelante lo cambiaré.
> 
> Otra cosa a que referías con lo de la review?

Es también una lista. Imagínate que tienes que ir de una peli a todas las reseñas que hay de ella. La única forma de hacerlo es examinar uno por uno todos los objetos de la lista.

**Comment by JoseJordanF** [comment]
Pero

> > Vale, pues más adelante lo cambiaré.
> > Otra cosa a que referías con lo de la review?
> 
> Es también una lista. Imagínate que tienes que ir de una peli a todas las reseñas que hay de ella. La única forma de hacerlo es examinar uno por uno todos los objetos de la lista.

El caso es que Kotlin tiene metodos muy utiles, por lo que puedo sacar esa lista en una linea de codigo con la funcion filter{}, filtrando por el ID de la pelicula que me interese.

**Comment by JJ** [comment]
> Pero
> 
> > > Vale, pues más adelante lo cambiaré.
> > > Otra cosa a que referías con lo de la review?
> > 
> > 
> > Es también una lista. Imagínate que tienes que ir de una peli a todas las reseñas que hay de ella. La única forma de hacerlo es examinar uno por uno todos los objetos de la lista.
> 
> El caso es que Kotlin tiene métodos muy útiles, por lo que puedo sacar esa lista en una línea de código con la función filter{}, filtrando por el ID de la película que me interese.(Aunque esta función internamente haga lo mismo)

No se trata de que sea fácil con el lenguaje, claro que lo es. Se trata de que la estructura de datos que se use sea la más eficiente.

**Comment by JoseJordanF** [comment]
> > Pero
> > > > Vale, pues más adelante lo cambiaré.
> > > > Otra cosa a que referías con lo de la review?
> > > 
> > > 
> > > Es también una lista. Imagínate que tienes que ir de una peli a todas las reseñas que hay de ella. La única forma de hacerlo es examinar uno por uno todos los objetos de la lista.
> > 
> > 
> > El caso es que Kotlin tiene métodos muy útiles, por lo que puedo sacar esa lista en una línea de código con la función filter{}, filtrando por el ID de la película que me interese.(Aunque esta función internamente haga lo mismo)
> 
> No se trata de que sea fácil con el lenguaje, claro que lo es. Se trata de que la estructura de datos que se use sea la más eficiente.

Vale vale, podria hacerlo con un hashMap asociando la ID de la peli a un conjunto de reviews y listo seria O(1) para la mayoria de operaciones
