### ISSUE TITLE
Justifica las marcas que uses

### ISSUE THREAD

**Issue by JJ** [JoseJordanF/Claqueta#13]
En este caso, supongo que será para el linting de TeX

https://github.com/JoseJordanF/Claqueta/blob/bb176c901ef00dddcac6e217952b640e10263103/doc/secciones/01_introduccion.tex#L56

Pero tienes que justificar para #1 que lo has hecho así para preservar la calidad del texto y poder hacer comprobación ortográfica en varios idiomas (o para lo que sea).

**Comment by JoseJordanF** [comment]
De acuerdo JJ, pero donde especifico esto en el #1, me refiero, no es algo que deba escribir en la memoria, sino simplemente justificar en la descripción de #1

**Comment by JJ** [comment]
> De acuerdo JJ, pero donde especifico esto en el #1, me refiero, no es algo que deba escribir en la memoria, sino simplemente justificar en la descripción de #1

Lo puedes justificar, por qué no. Una de las rúbricas hablar de la preocupación por la calidad, y esto es claramente eso
