### ISSUE TITLE
¿Puede haber una forma más eficiente de comprobar si un usuario existe o no?

### ISSUE THREAD

**Issue by JJ** [JoseJordanF/Claqueta#131]
¿Que usar `contains` que recorre toda la lista y es O(n)?

https://github.com/JoseJordanF/Claqueta/blob/f24c0e5aa6ae3924846257bf6dff72c4f02daa63/claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManager.kt#L45

¿Hay alguna parte de la lógica de negocio que requiera que hay que acceder a los nombres de usuario uno detrás de otro? ¿Si lo hay, se usa más o menos a menudo que el comprobar si un usuario existe?

**Comment by JoseJordanF** [comment]
No entiendo por qué dices, uno detrás de otro.

**Comment by JJ** [comment]
¿Qué es una lista?

```Kotlin
var users: List<String> = listOf(),
```

De veras, Jose, haz un pequeño esfuerzo por entener lo que estoy diciendo, que es tu propio código.

**Comment by JoseJordanF** [comment]
Es la forma en que lo dices el porqué no lo entiendo, lo siento

**Comment by JJ** [comment]
En todo caso como #128 no es una cosa que requiera atención inmediata, pero sí antes de que esto vaya a ir a una base de datos.

**Comment by JoseJordanF** [comment]
Okay, aunque sigo sin ver el problema de comprobar si existe un usuario antes de crearlo

**Comment by JJ** [comment]
> Es la forma en que lo dices el porqué no lo entiendo, lo siento

Es un mínimo detalle de lo que digo. También digo que buscar un elemento en la lista es O(n) y que mires como se comporta contains.

**Comment by JoseJordanF** [comment]
A okay por tema de eficiencia

**Comment by JJ** [comment]
> Okay, aunque sigo sin ver el problema de comprobar si existe un usuario antes de crearlo

¿Es eso lo que entiendes de "Puede haber una forma más eficiente de comprobar si un usuario existe o no"? ¿Que no hay que comprobarlo?

**Comment by JoseJordanF** [comment]
No, pero hubiera requerido menos mensajes, directamente la pregunta. ¿Puede haber una forma más eficiente de comprobar si un usuario existe?

**Comment by JJ** [comment]
(Aunque desde luego si el sistema generara un nombre de usuario no habría que comprobarlo. No hay *ninguna* historia de usuario que diga que tiene que elegirlo el usuario y por tanto comprobar si ya lo ha elegido otra persona o no)

**Comment by JJ** [comment]
> No, pero hubiera requerido menos mensajes, directamente la pregunta. ¿Puede haber una forma más eficiente de comprobar si un usuario existe?

Jose, es el título del issue.

**Comment by JoseJordanF** [comment]
Por lo del nombre es logico que el usuario introduzca su propio nombre de usuario no creia que fuera necesario añadirlo en una HU.

Por lo del título, lo siento, no me lo tengas en cuenta, me siento abrumado por tantos mensajes, la verdad. Perdona no estar atento, parezco un pato mareado.

**Comment by JJ** [comment]
> Por lo del nombre es logico que el usuario introduzca su propio nombre de usuario no creia que fuera necesario añadirlo en una HU.
> 

Como cualquier otra cosa, es algo que debe especificarse en una HU o HD. En un PMV yo creo que da un poco igual, y en un producto más adelante, basta con que asocies un ID interno a un nombre y/o nick. Aquí lo que tienes en el array es simplemente un identificador único por cada usuario. 

Perdona por el bombardeo, pensé que abrir issues sería más eficiente que ponerlo como comentarios, pero ya veo que no es así. En todo caso, trataré de abrir *menos* de una vez

**Comment by JoseJordanF** [comment]
Si básicamente es solo una cadena, pero si podría tratarlo como id internos a los que luego asociarlos al nick que introduzca el usuario.

Y no te disculpes, yo estoy demasiado cuajado. También es verdad que aunque ya lo hemos hablado, sobre todo al principio pienso que el contacto humano evitaría varias confusiones y permitiría un entendimiento más temprano de los conceptos. Pero bueno, ya sé que no es ni eficiente ni posible, no te daré más la tabarra con ello 😂

**Comment by JJ** [comment]
Mi experiencia me dice que el contacto humano lo único que produce es un montón de "¿por qué no has hecho esto como ya hablamos en la reunión?" Los issues y comentarios pueden enlazarse, borrarse, resolverse, y editarse y todo lo que haga falta.
