### ISSUE TITLE
Incide claramente en los aspectos "sociales" de las reseñas

### ISSUE THREAD

**Issue by JJ** [JoseJordanF/Claqueta#15]
En estas líneas hablas de las reseñas como punto de encuentro

https://github.com/JoseJordanF/Claqueta/blob/bb176c901ef00dddcac6e217952b640e10263103/doc/secciones/01_introduccion.tex#L98

En las historias de usuario correspondientes tendrás que hacer énfasis en estos aspectos sociales, convirtiéndolo en objetivos del proyecto.

**Comment by JoseJordanF** [comment]
Vale entonces las historias de usuario las situaré en el capítulo 2. Y en el capítulo 4 solo las mencionaré como parte de la metodología
