### ISSUE TITLE
En los user journey tienes que especificar claramente cuando se plantea el problema

### ISSUE THREAD

**Issue by JJ** [JoseJordanF/Claqueta#16]
https://github.com/JoseJordanF/Claqueta/blob/bb176c901ef00dddcac6e217952b640e10263103/doc/secciones/02_descripcion.tex#L8

En función de eso, hará falta un tipo de aplicación u otra: app, web, las dos cosas con un backend detrás, bot de Telegram... El tipo de aplicación emerge de la metodología, no se establece de antemano.

**Comment by JoseJordanF** [comment]
Vale como parte del problema plantearé que puede ser de ambas formas. Finalizando en el capítulo 4 con la decisión de la app Android por x razones.
