### ISSUE TITLE
INTRODUCCIÓN: Descripción, motivación y contexto histórico

### ISSUE THREAD

**Issue by JoseJordanF** [JoseJordanF/Claqueta#2]
En primer lugar, es necesario plantear el problema, y entenderlo. Para dar una solución mediante la ingeniería del software y describir esto en la memoria para satisfacer al #1. Para ello habrá que escribir en la introducción de la memoria una clara descripción del problema, la motivación que lleva a dicho problema y los objetivos que se pretenden cumplir.

**Comment by JoseJordanF** [comment]
📝 33d234d

**Comment by JoseJordanF** [comment]
📝 Introducción: comprensión y contexto del trabajo #2:  33d234d

**Comment by JJ** [comment]
> Para ello habrá que escribir en la introducción de la memoria una clara descripción del problema, la motivación que lleva a dicho problema y los objetivos que se pretenden cumplir.

Los issues no plantean lo que hay que hacer, sólo el problema a resolver. Lo que hay que hacer para resolverlo nunca tiene una sola opción; se justificará la opción que se ha tomado en los mensajes de commit.

En este caso planteas una única opción: escribir *en la introducción*. Sin embargo, cosas como el contexto podrían estar mejor en otro capítulo (el estado del arte, por ejemplo). El que vaya en uno u otro lado son decisiones que tienes que tomar para satisfacer de la mejor forma posible #1

**Comment by JoseJordanF** [comment]
Entonces cosas como el tema de los espacios que hay hoy día para compartir tus reseñas si deberían ir en mejor lugar, como en el estado del arte. Pero entonces no me queda claro que debe ir en la introducción, aparte de la definición de reseña, y algunas menciones de artículos, famosos críticos e historia de la reseña cinematográfica.

Puede que me haya centrado simplemente en hacer una introducción contundente y no darme cuenta de que algunas partes irían mejor en otras secciones del trabajo.

**Comment by JJ** [comment]
La introducción describe el problema, los objetivos y los usuarios, en general. Pero como en todo el resto, son decisiones que tienes que tomar tú. Lo principal no es qué tiene que ir en cada sitio, sino que los issues no deben describir soluciones, sólo plantear problemas.

**Comment by JoseJordanF** [comment]
Los nuevos issues representarán problemas y no soluciones. Con respecto a la introducción es que  me lleva a una gran contradicción porque si la introducción describe el problema y los objetivos. En la sección descripción del problema sería redundante. Es algo que no me termina de quedar claro
