### ISSUE TITLE
En que capitulo debo decidir que tipo de aplicación desarrollar

### ISSUE THREAD

**Issue by JoseJordanF** [JoseJordanF/Claqueta#27]
Debo decidir que tipo de aplicación desarrollar, aplicación web, móvil… Pero donde llevo a cabo esa discusión y esa conclusión. Una vez descrito el problema en el capítulo 2, podría haber varios sitios donde decidirlo. En el capítulo 3 del estado del arte o en el capítulo 4 de la planificación. Este problema está relacionado con la #1 y a su vez con el M0, ya que al tribunal le gustaría saber por qué decido desarrollar un tipo de aplicación u otro. De esta manera forma parte del M0 por ser parte de la descripción de una posible solución al problema planteado.

**Comment by JJ** [comment]
Todos los issues tienen que estar relacionados con una historia de usuario, o es imposible dilucidar cómo añaden valor al cliente. Por otro lado, trata de que la asignación a milestones no sea arbitraria, sino aclara cómo contribuye este issue al milestone en el que está asignado.
