### ISSUE TITLE
Cuantos objetos necesito definir referentes a la resolución de HU

### ISSUE THREAD

**Issue by JoseJordanF** [JoseJordanF/Claqueta#30]
Es importante saber cuantos objetos debo definir, en todo caso siempre se puede volver atrás y definir más objetos si es necesario. #1

**Comment by JJ** [comment]
Realmente no es muy importante. Simplemente asegúrate que los objetos que defines son los suficientes para cubrir el PMV del milestone en el que te encuentres.
Recuerda en todo caso que los issues plantean siempre problemas, y no son metodológicos. Y que siempre tienen que ir ligados a una HU y a un milestone.

**Comment by JoseJordanF** [comment]
Cierto siempre se me olvida que los issues van ligados a las HU
