### ISSUE TITLE
Como sería la lógica de negocio según el "Aficionado"

### ISSUE THREAD

**Issue by JoseJordanF** [JoseJordanF/Claqueta#32]
La lógica de negocio son las funciones o reglas que determinan como funciona tu aplicación, y estas dependen de las necesidades y los propósitos de dicha aplicación. Por ello hay que recurrir a las necesidades de los clientes como los aficionados, en este caso para saber cuáles podrían ser esas operaciones.

**Comment by JJ** [comment]
Los issues deben ser un poco más concretos, y siempre enlazar la HU a la que se refieran.

**Comment by JoseJordanF** [comment]
Vale crearé las historias de usuario para tenerlas poder referenciarlas

**Comment by JJ** [comment]
Ah, por supuesto. Asumía que las habías creado...

**Comment by JJ** [comment]
Y por cierto, las HUs y toda la configuración inicial sería parte del [M0](https://github.com/JoseJordanF/Claqueta/milestone/1). Recuerda que los  milestones están para medir el avance el proyecto. Hasta que no hayas terminado uno (y no lo has hecho) no puedes empezar el siguiente. Y si estás empezando el 2 antes del 1, es que o no estás entendiendo bien el concepto de milestone (como producto mínimamente viable) o no tienes bien planteada la organización y secuencia de los mismos.
