### ISSUE TITLE
Las historias de usuario no están asignadas a milestones

### ISSUE THREAD

**Issue by JJ** [JoseJordanF/Claqueta#40]
Porque no representan problemas; se usa el formato de issue por conveniencia, pero realmente no dan lugar a código que se inserte en los productos mínimamente viables correspondientes.

**Comment by JoseJordanF** [comment]
Luego, desligo la historia del tribunal del M0

**Comment by JJ** [comment]
Eso para empezar... No he visto las otras.

**Comment by JoseJordanF** [comment]
Las otras no estaban asignadas, no sé por qué asigne el M1 a la #1

**Comment by JJ** [comment]
El tema es que no sé si eso es el único problema que hay o hay otros. Puedes haberlo puesto en la documentación, por ejemplo. Se trata simplemente de que apliques ese principio, y entiendas por qué.

**Comment by JoseJordanF** [comment]
No, diría que la documentación no las he relacionado con los milestone. Pero sí entiendo que las HU no definen problemas, sino que exponen las necesidades o peticiones del usuario relacionadas con el problema.
