### ISSUE TITLE
¿Es una reseña una entidad?

### ISSUE THREAD

**Issue by JoseJordanF** [JoseJordanF/Claqueta#66]
#37

**Comment by JJ** [comment]
Tampoco está asignado a ninguna HU.

**Comment by JJ** [comment]
Hoy he leído, por cierto, sobre el [problema XY](https://xyproblem.info/), que es preguntar sobre la solución que piensas en vez de plantear el problema que quieres solucionar. Este issue sería un ejemplo de eso. Sólo quieres saber si es una entidad o un objeto valor, pero el problema que tienes que resolver es qué es realmente una reseña y cómo hacer un modelo de ella de forma que puedas usarlo en la lógica de negocio.

**Comment by JoseJordanF** [comment]
Sii realmente es eso, pienso que lo único que me faltaba es la manera de identificar de manera única cada reseña, los demás atributos los tengo bastante claros

**Comment by JJ** [comment]
No se trata de que los tengas claros. Si "tenerlos claros" fuera suficiente para desarrollar, se escribiría el código y listo. La cuestión es que tienes que entenderlo dentro de 6 meses mirando al código y yo tengo que entender si has seguido la metodología o no. Las metodologías están para eso, para garantizar una creación eficiente del código y una transmisión eficiente del conocimiento entre los diferentes miembros del equipo.
