### ISSUE TITLE
El usuario debe escribir solo una review para cada película

### ISSUE THREAD

**Issue by JoseJordanF** [JoseJordanF/Claqueta#69]
#37

**Comment by JJ** [comment]
Una vez más, enlaza una HU. Y esto es más bien una característica de las review que un issue diferente.

**Comment by JoseJordanF** [comment]
Si, hay issues que podrían a varios issues que he creado

**Comment by JoseJordanF** [comment]
(43ce564af4ea341f3c50e8e6257e0f93387dd9e5)
