### ISSUE TITLE
¿Cómo hago referencia a las reseñas de cada película?

### ISSUE THREAD

**Issue by JoseJordanF** [JoseJordanF/Claqueta#78]
#37

**Comment by JJ** [comment]
Siempre debes enlazar una historia de usuario, y proporcionar todo el contexto que necesites.
Con el código que has incluido aquí es difícil, o imposible, saber si se ha resuelto este problema o no.

**Comment by JoseJordanF** [comment]
Lo entiendo, pero no se para mi es algo obvio, si hemos hablado en toda la memoria de reseñas de películas. Debe existir una forma de enlazar esas reseñas a cada película. No veo que sea algo que represente una historia de usuario, si acaso del programador. Por esa parte no entiendo a que te refieres.

**Comment by JJ** [comment]
Los issues no se hacen para ti, ahora. Se hacen para el tú del futuro, para mi y para #1 
Una metodología de desarrollo tiene que decirte dos cosas: qué hago ahora y si lo que hago está bien. El enlazar HUs es para responder a la segunda (también la primera, porque las HUs deben estar ordenadas). Algo está bien si resuelve un problema del cliente. Los problemas del cliente están en las HUs. Por lo tanto, es imposible valorar si algo está bien (modelo, código) si no se sabe de qué forma puede afectar al cliente.

**Comment by JoseJordanF** [comment]
Que enlace las reseñas a las películas, significa que el cliente podrá escribir reseñas dirigidas a esa película, en concreto, de ahí este issue

**Comment by JJ** [comment]
Cómo acceda a las películas es un detalle de implementación. Que no se represente de esta forma no quiere decir que no pueda acceder.

**Comment by JoseJordanF** [comment]
O sea que no es necesaria esa asociación, solo para mí como programador en un futuro

**Comment by JJ** [comment]
Creo que estamos hablando de cosas diferentes. En este issue lo único que te estoy diciendo es que enlaces una historia de usuario, la que sea.
En el código en si hay otros problemas que te he comentado in situ.

**Comment by JoseJordanF** [comment]
Vale he enlazado una en la descripción, y si ya he contestado a tus comentarios sobre el código.

**Comment by JoseJordanF** [comment]
(28a26f358ad267387e8521bd3a5a20dca3885290)
