### ISSUE TITLE
Que ocurre cuando un usuario crea una reseña

### ISSUE THREAD

**Issue by JoseJordanF** [JoseJordanF/Claqueta#87]
#38  El crítico quiere que sus reseñas ayuden al resto de usuarios, pero debe poder crear esas reseñas, como se crean, y como guarda relación con la película y su autor

**Comment by JJ** [comment]
Hombre, pon un poquito más, hombre... Si lo has hecho como *placeholder* vale, pero un issue debe describir un problema y el contexto que tiene.

**Comment by JoseJordanF** [comment]
Sisi ahora paso uno por uno
