### ISSUE TITLE
Compila el LaTeX sólo cuando, y siempre que, cambie algo afectado

### ISSUE THREAD

**Issue by JJ** [JoseJordanF/Claqueta#9]
https://github.com/JoseJordanF/Claqueta/blob/b5b933dab9cfe684faee4292e66d4bf3635846a1/.github/workflows/Compile-LateX.yml#L5

En este caso compilas siempre, también cuando salga el código... Por otro lado, no compila si estás en una rama, así que el problema es que no vas a encontrar errores de compilación hasta que no incorpores a la rama principal.

**Comment by JoseJordanF** [comment]
Solo debo compilar cuando hay algún cambio en el documento, perfecto

**Comment by JJ** [comment]
Recuerda asignar esto a un Milestone.

**Comment by JoseJordanF** [comment]
asignado

**Comment by JJ** [comment]
... y efectivamente llevarlo a cabo para poder terminal el milestone.

**Comment by JoseJordanF** [comment]
De esta forma quedaria bien?

(https://github.com/JoseJordanF/Claqueta/commit/b726505b98c6923f0330b5bb8f5ba1b8544581d8)

**Comment by JJ** [comment]
> De esta forma quedaría bien?, y cierro ya este issue
> 
> ([b726505](https://github.com/JoseJordanF/Claqueta/commit/b726505b98c6923f0330b5bb8f5ba1b8544581d8))

** se refiere a cualquier cantidad de directorios. Lo correcto sería `**/*.bib` y `**/*.tex`

**Comment by JoseJordanF** [comment]
Okay, lo cambio y cierro
